### ISSUE TITLE
IllegalArgumentException: No implementation of method: :urls of protocol: #'clojure.java.classpath/URLClasspath

### ISSUE THREAD

**Issue by nfedyashev** [juxt/joplin#117]
Any hints on what might be causing this exception or how it can be solved are greatly appreciated. First time joplin user.

>Caused by: java.lang.IllegalArgumentException: No implementation of method: :urls of protocol: #'clojure.java.classpath/URLClasspath found for class: jdk.internal.loader.ClassLoaders$AppClassLoader

```
Exception in thread "main" Syntax error compiling at (/tmp/form-init15619014219665837408.clj:1:74).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No implementation of method: :urls of protocol: #'clojure.java.classpath/URLClasspath found for class: jdk.internal.loader.ClassLoaders$AppClassLoader
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at clojure.java.classpath$fn__51514$G__51509__51519.invoke(classpath.clj:25)
	at clojure.java.classpath$loader_classpath.invokeStatic(classpath.clj:61)
	at clojure.java.classpath$loader_classpath.invoke(classpath.clj:58)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1788)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$mapcat.invokeStatic(core.clj:2783)
	at clojure.core$mapcat.doInvoke(core.clj:2783)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.java.classpath$classpath.invokeStatic(classpath.clj:67)
	at clojure.java.classpath$classpath.invoke(classpath.clj:63)
	at clojure.java.classpath$classpath.invokeStatic(classpath.clj:72)
	at clojure.java.classpath$classpath.invoke(classpath.clj:63)
	at clojure.java.classpath$classpath_directories.invokeStatic(classpath.clj:77)
	at clojure.java.classpath$classpath_directories.invoke(classpath.clj:74)
	at joplin.core$get_files.invokeStatic(core.clj:80)
	at joplin.core$get_files.invoke(core.clj:73)
	at joplin.core$get_migration_namespaces.invokeStatic(core.clj:109)
	at joplin.core$get_migration_namespaces.invoke(core.clj:104)
	at joplin.core$get_migrations.invokeStatic(core.clj:127)
	at joplin.core$get_migrations.invoke(core.clj:123)
	at fooapp_joplin.elasticsearch.database$fn__52127.invokeStatic(database.clj:86)
	at fooapp_joplin.elasticsearch.database$fn__52127.doInvoke(database.clj:85)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:660)
	at joplin.repl$reset.invokeStatic(repl.clj:73)
	at joplin.repl$reset.doInvoke(repl.clj:69)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at db$test_prepare.invokeStatic(db.clj:216)
	at db$test_prepare.doInvoke(db.clj:194)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval11365.invokeStatic(form-init15619014219665837408.clj:1)
	at user$eval11365.invoke(form-init15619014219665837408.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
```

Context:

```
 java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1deb10u1, mixed mode, sharing)

clojure
Clojure 1.10.1

 cat project.clj | grep joplin
                 [joplin.core "0.3.11"]

```

fooapp_joplin.elasticsearch.database.clj file(with corresponding line numbers): 
```
85 (defmethod rollback-db :foappp-es [target amount-or-id & args]
86  (apply do-rollback (get-migrations (:migrator target))
87         (->ESDatabase target) amount-or-id args))
```

**Comment by nfedyashev** [comment]
Sorry, seems like I was using the wrong jdk version
