### ISSUE TITLE
migrate-db from test does not find migrators

### ISSUE THREAD

**Issue by sveri** [juxt/joplin#64]
Hi,

I am trying to migrate a database from a test. This is my folder layout

project
-> test/clj/namespace/user_test.clj
-> resources/migrators/sqlite/user.[up|down].sql

my user_test looks like this (plus some tests):

    (j/migrate-db
      {:db {:type :jdbc,
            :url "jdbc:sqlite::memory:"}
       :migrator "migrators/sqlite"})

When I run `lein test` I get this stacktrace:
Warning, no migrators found!
Migrating #joplin.sql.database.SqlDatabase{:db {:type :jdbc, :url jdbc:sqlite::memory:}, :migrator migrators/sqlite, :connection-uri jdbc:sqlite::memo
ry:}
Exception in thread "main" java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: ragtime_migrations), compiling:(foo/bar
/db/user_test.clj:19:1)
        at clojure.lang.Compiler.load(Compiler.java:7249)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:362)
        at clojure.lang.RT.load(RT.java:446)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5446.invoke(core.clj:5862)
        at clojure.core$load.doInvoke(core.clj:5861)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5667)
        at clojure.core$load_lib$fn__5395.invoke(core.clj:5707)
        at clojure.core$load_lib.doInvoke(core.clj:5706)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$load_libs.doInvoke(core.clj:5745)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$require.doInvoke(core.clj:5828)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:630)
        at user$eval136.invoke(form-init1675116507402864902.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6792)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.load(Compiler.java:7237)
        at clojure.lang.Compiler.loadFile(Compiler.java:7175)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: ragtime_migrations)
        at org.sqlite.core.DB.newSQLException(DB.java:890)
        at org.sqlite.core.DB.newSQLException(DB.java:901)
        at org.sqlite.core.DB.throwex(DB.java:868)
        at org.sqlite.core.NativeDB.prepare(Native Method)
        at org.sqlite.core.DB.prepare(DB.java:211)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:251)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:223)
        at clojure.java.jdbc.deprecated$prepare_statement.doInvoke(deprecated.clj:479)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:632)
        at clojure.java.jdbc.deprecated$with_query_results_STAR_.invoke(deprecated.clj:675)
        at joplin.sql.database.SqlDatabase$fn__2560.invoke(database.clj:51)
        at clojure.java.jdbc.deprecated$with_connection_STAR_.invoke(deprecated.clj:307)
        at joplin.sql.database.SqlDatabase.applied_migration_ids(database.clj:49)
        at ragtime.core$applied_migrations.invoke(core.clj:31)
        at ragtime.core$migrate_all.invoke(core.clj:57)
        at ragtime.core$migrate_all.invoke(core.clj:53)
        at joplin.core$do_migrate.invoke(core.clj:140)
        at joplin.jdbc.database$eval2726$fn__2727.doInvoke(database.clj:84)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at foo.bar.db.user_test$eval2764.invoke(user_test.clj:19)
        at clojure.lang.Compiler.eval(Compiler.java:6792)
        at clojure.lang.Compiler.load(Compiler.java:7237)
        ... 33 more

These are the deps I have:

                 [org.xerial/sqlite-jdbc "3.8.7"]
                 [joplin.core "0.2.11"]
                 [joplin.jdbc "0.2.11"]

Running `lein joplin migrate...` with the same path given everything works as expected.

**Comment by sveri** [comment]
I just debugged `migrate-db` and it seems like `get-migration-namespaces` only returns *.clj files:

    (map #(re-matches #"(.*)(\.clj)$" %))

Is that true? This means that .sql migrations are not supported when running joplin from code?

**Comment by oliyh** [comment]
It looks like your database type should be `:sql` rather than `:jdbc` if you are using .sql migrator files - this change was introduced in #7.

**Comment by sveri** [comment]
Thank you very much. I wasn't aware of the difference between the both. So now my call looks like this:

    (j/migrate-db
      {:db {:type :sql,
            :url "jdbc:sqlite::memory:"}
       :migrator "resources/migrators/sqlite"})

Which seems to find my sql files, but somewhere in: `joplin.jdbc.database#get-sql-migrations'` they get filtered out so that the function returns an empty list. It's hard for me to figure out where exactly, but I might keep on trying. Anything else I may be doing wrong here?

**Comment by sveri** [comment]
Ok, figured that one out too, the problem was the jdbc uri being not named. Using something likes this: `"jdbc:sqlite:memory:foo"` works as expected. So thanks for the clarification with the :sql type.

**Comment by craigglennie** [comment]
Would you mind providing the full config that you used to get ragtime working with a SQLite in-memory DB? I've tried adding the database name to the JDBC URI (I have :jdbc:sqlite::memory:my-db) and it ends up creating a file on disk called :memory:my-db, which makes me think it's not in-memory after all.

**Comment by sveri** [comment]
@craigglennie Sorry, this is almost half a year old and I just had a quick look, but could not find it anymore. If I ever see it again I will post back.
Looking at the docs: https://www.sqlite.org/inmemorydb.html it seems like this string should be enough ":memory:" without a name.

**Comment by oliyh** [comment]
@craigglennie I think it won't work with just `:memory:` because SQLite will create a new in-memory database each time you create a connection to that URI. Because Joplin creates its own connection, any database Joplin migrates may not be the same database your application has a connection to.

Supplying a name like `my-db` allows you to have multiple connections to the same database and, according to the docs that @sveri linked to, the database will still remain in memory most of the time but could be flushed to disk if it gets too large.
